webdriver:
  browser: chrome
  headless: false
log_level: Logger::DEBUG

timeout:
  click: 1
  short: 8
  medium: 30
  long: 240

deployment: core

core:
  base_url: https://core-dev.cspace.berkeley.edu
  admin:
    username: admin@core.collectionspace.org
    password: Administrator

core_ucb:
  base_url: https://core-qa.cspace.berkeley.edu
  admin:
    username: secret
    password: secret
  batch_user:
    username: batch-test@core.collectionspace.org
    password: DataUpdates
  report_user:
    username: report-test@core.collectionspace.org
    password: Reporter

bampfa:
  base_url: https://bampfa-qa.cspace.berkeley.edu
  admin:
    username: secret
    password: secret

botgarden:
  base_url: https://botgarden-qa.cspace.berkeley.edu
  admin:
    username: secret
    password: secret

cinefiles:
  base_url: https://cinefiles-qa.cpace.berkeley.edu
  admin:
    username: secret
    password: secret

pahma:
  base_url: https://pahma-qa.cspace.berkeley.edu
  admin:
    username: secret
    password: secret

ucjeps:
  base_url: https://ucjeps-qa.cspace.berkeley.edu
  admin:
    username: secret
    password: secret
